import os
import tempfile
import difflib
from pathlib import Path
from lxml import etree
from xmldiff import main

def get_latest_xml_files(directory):
    path = Path(directory)
    xml_files = list(path.glob('*.xml'))
    if len(xml_files) == 0:
        return None
    
    file_info = []
    import datetime
    for f in xml_files:
        try:
            tree = etree.parse(str(f))
            root = tree.getroot()
            date_str = root.get('date-created')
            if date_str:
                file_info.append((date_str, f))
            else:
                # Fallback to file mtime formatted as ISO string
                mtime = os.path.getmtime(str(f))
                dt = datetime.datetime.fromtimestamp(mtime).astimezone()
                file_info.append((dt.isoformat(), f))
        except Exception:
            mtime = os.path.getmtime(str(f))
            dt = datetime.datetime.fromtimestamp(mtime).astimezone()
            file_info.append((dt.isoformat(), f))
    
    # Sort by the timestamp (date-created string or mtime)
    file_info.sort(key=lambda x: x[0])
    
    if len(file_info) == 1:
        # Only one spec exists — bootstrap case; diff against a null spec
        return None, file_info[-1][1]
    
    return file_info[-2][1], file_info[-1][1]

NULL_SPEC_XML = """<?xml version='1.0' encoding='utf-8'?>
<specification_set date-created="" />"""


def _node_text(spec, tag):
    node = spec.find(tag)
    if node is None or node.text is None:
        return ""
    return node.text.strip()


def _summarize_text(text, limit=120):
    cleaned = " ".join((text or "").split())
    if len(cleaned) <= limit:
        return cleaned
    return cleaned[: limit - 3] + "..."


def _patch_block(label, old_text, new_text):
    old_lines = (old_text or "").splitlines()
    new_lines = (new_text or "").splitlines()
    diff_lines = list(
        difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=f"old/{label}",
            tofile=f"new/{label}",
            lineterm="",
        )
    )
    if not diff_lines:
        return f"{label}: <no textual changes>"
    return f"{label}:\n" + "\n".join(diff_lines)


def _spec_ref(spec):
    return spec.get("ref") or spec.get("type")


def _specs_by_ref(root):
    specs = {}
    for spec in root.xpath("//specification"):
        ref = _spec_ref(spec)
        if ref:
            specs[ref] = spec
    return specs


def _libspec_version(root):
    return root.get("libspec-version") or ""


def _major_version(version):
    major = version.split(".", 1)[0].strip()
    return int(major) if major.isdigit() else None


def _major_versions_compatible(old_root, new_root):
    old_major = _major_version(_libspec_version(old_root))
    new_major = _major_version(_libspec_version(new_root))
    return old_major is None or new_major is None or old_major == new_major


def _version_mismatch_message(old_file, new_file, old_root, new_root):
    return (
        "Error: refusing to diff specs generated by different libspec major versions "
        f"({old_file.name}: {_libspec_version(old_root) or '<missing>'}, "
        f"{new_file.name}: {_libspec_version(new_root) or '<missing>'}).\n"
        "Workaround: regenerate both XML specs with the same libspec major version, "
        "usually by rebuilding the older project commit with the current libspec, "
        "then rebuilding the current commit and diffing those generated files.\n"
        "See docs/cross-major-version-diffs.org for the full workflow and edge cases."
    )


def get_specs_for_diff(dir_arg):
    """Return (old_file, new_file, old_tree, new_root) for diffing."""
    files = get_latest_xml_files(dir_arg)
    if not files:
        return None, None, None, None

    old_file, new_file = files

    if old_file is None:
        try:
            new_tree = etree.parse(str(new_file))
            new_root = new_tree.getroot()
            return None, new_file, None, new_root
        except Exception as e:
            print(f"Error parsing XML: {e}")
            return None, None, None, None
    else:
        try:
            new_tree = etree.parse(str(new_file))
            new_root = new_tree.getroot()
            return old_file, new_file, None, new_root
        except Exception as e:
            print(f"Error parsing XML: {e}")
            return None, None, None, None


def generate_patch(dir_arg):
    """Generate a structured diff between the two latest XML specs."""
    old_file, new_file, _, new_root = get_specs_for_diff(dir_arg)
    if new_file is None:
        print("Error: No XML spec files found in the directory.")
        return

    try:
        old_root = etree.fromstring(NULL_SPEC_XML) if old_file is None else etree.parse(str(old_file)).getroot()
        if not _major_versions_compatible(old_root, new_root):
            print(_version_mismatch_message(old_file, new_file, old_root, new_root))
            return
    except Exception as e:
        print(f"Error parsing XML: {e}")
        return

    if old_file is None:
        print(f"Diffing State: <null spec> -> {new_file.name}")
    else:
        print(f"Diffing State: {old_file.name} -> {new_file.name}")
    print("=" * 60)

    diffs = _xml_diffs(old_file, new_file)
    if not diffs:
        print("No changes detected.")
        return

    old_specs = {s.get('type'): s for s in old_root.xpath('//specification')}
    new_specs = {s.get('type'): s for s in new_root.xpath('//specification')}
    new_specs_by_ref = _specs_by_ref(new_root)

    all_components = sorted(set(old_specs.keys()) | set(new_specs.keys()))
    
    # 1. Identify changed components and collect their changes
    diff_entries = []
    for comp_type in all_components:
        old_spec = old_specs.get(comp_type)
        new_spec = new_specs.get(comp_type)
        if old_spec is None:
            diff_entries.append(('NEW', comp_type, old_spec, new_spec, []))
        elif new_spec is None:
            diff_entries.append(('REMOVED', comp_type, old_spec, new_spec, []))
        else:
            changes = _compare_specs(old_spec, new_spec)
            if changes:
                diff_entries.append(('CHANGED', comp_type, old_spec, new_spec, changes))

    # 2. Pre-scan for shared non-template superspecs among ONLY those in diff_entries
    shared_superspecs = {} # ref -> spec_node
    for entry in diff_entries:
        action, comp_type, old_spec, new_spec, changes = entry
        target_spec = new_spec if action != 'REMOVED' else None
        if target_spec is None:
            continue
        
        inherits = [e.text for e in target_spec.xpath('inherits/ref')]
        inherited_specs_list, _ = _inherited_specs(inherits, new_specs_by_ref)
        for ref, _, spec_node in inherited_specs_list:
            is_template = spec_node.get("template") == "true"
            if spec_node.get("template") is None:
                # Fallback for older XML specs
                req_text = _node_text(spec_node, "docstring") or _node_text(spec_node, "docstring_template") or ""
                is_template = "{{" in req_text or "{%" in req_text
            
            if not is_template:
                shared_superspecs[ref] = spec_node

    if shared_superspecs:
        print("Shared Superspecs (Non-Template):")
        print("-" * 40)
        for ref in sorted(shared_superspecs.keys()):
            spec_node = shared_superspecs[ref]
            spec_name = spec_node.get("type") or ref.rsplit(".", 1)[-1]
            print(f"  {spec_name}: {ref}")
            requirement_text = _node_text(spec_node, "docstring") or _node_text(spec_node, "docstring_template")
            if requirement_text:
                print("    requirement:")
                for line in requirement_text.splitlines():
                    print(f"      {line}")
            print()
        print("=" * 60)

    # 4. Print individual diffs
    for entry in diff_entries:
        action, comp_type, old_spec, new_spec, changes = entry
        if action == 'NEW':
            print(f"\n[NEW] {comp_type}")
            _print_spec(new_spec, new_specs_by_ref, shared_superspecs)
        elif action == 'REMOVED':
            print(f"\n[REMOVED] {comp_type}")
        elif action == 'CHANGED':
            print(f"\n[CHANGED] {comp_type}")
            for change in changes:
                print(f"  - {change}")
            _print_inherited_context(new_spec, new_specs_by_ref, shared_superspecs)


def _xml_diffs(old_file, new_file):
    if old_file is not None:
        return main.diff_files(str(old_file), str(new_file))

    with tempfile.NamedTemporaryFile(suffix='.xml', mode='w', delete=False) as tmp:
        tmp.write(NULL_SPEC_XML)
        tmp_path = tmp.name
    try:
        return main.diff_files(tmp_path, str(new_file))
    finally:
        os.unlink(tmp_path)


def _print_spec(spec, specs_by_ref=None, shared_superspecs=None):
    """Print the structured representation of a spec."""
    specs_by_ref = specs_by_ref or {}

    docstring = _node_text(spec, 'docstring')
    if docstring:
        print(f"  docstring: {_summarize_text(docstring)}")

    title = _node_text(spec, 'title')
    if title:
        print(f"  title: {title}")

    req_id = _node_text(spec, 'req_id')
    if req_id:
        print(f"  req_id: {req_id}")

    desc = _node_text(spec, 'description')
    if desc:
        print(f"  description: {_summarize_text(desc)}")

    notes = _node_text(spec, 'notes')
    if notes:
        print(f"  notes: {_summarize_text(notes)}")

    inherits = [e.text for e in spec.xpath('inherits/ref')]
    if inherits:
        _print_inherited_specs(inherits, specs_by_ref, shared_superspecs)

    eff_ids = [e.text for e in spec.xpath('effective_req_ids/id')]
    if eff_ids:
        print(f"  effective_req_ids: {', '.join(eff_ids)}")

    overrides = [e.text for e in spec.xpath('overrides/field')]
    if overrides:
        print(f"  overrides: {', '.join(overrides)}")

    deltas = spec.xpath('delta_requirements/*')
    if deltas:
        print("  delta_requirements:")
        for d in deltas:
            print(f"    {d.tag}: {d.text or ''}".strip())


def _compare_specs(old_spec, new_spec):
    """Compare two specs and return list of changes."""
    changes = []
    old_docstring = _node_text(old_spec, 'docstring')
    new_docstring = _node_text(new_spec, 'docstring')
    docstring_changed = old_docstring != new_docstring

    old_title = _node_text(old_spec, 'title')
    new_title = _node_text(new_spec, 'title')
    if old_title != new_title:
        changes.append(f"title: {old_title or '<missing>'} -> {new_title or '<missing>'}")

    old_req_id = _node_text(old_spec, 'req_id')
    new_req_id = _node_text(new_spec, 'req_id')
    if old_req_id != new_req_id:
        changes.append(f"req_id: {old_req_id or '<missing>'} -> {new_req_id or '<missing>'}")

    old_inherits = set(e.text for e in old_spec.xpath('inherits/ref|inherits/spec'))
    new_inherits = set(e.text for e in new_spec.xpath('inherits/ref|inherits/spec'))
    if old_inherits != new_inherits:
        changes.append(f"inherits: {old_inherits} -> {new_inherits}")

    old_eff = set(e.text for e in old_spec.xpath('effective_req_ids/id'))
    new_eff = set(e.text for e in new_spec.xpath('effective_req_ids/id'))
    if old_eff != new_eff:
        changes.append(f"effective_req_ids: {old_eff} -> {new_eff}")

    old_overrides = set(e.text for e in old_spec.xpath('overrides/field'))
    new_overrides = set(e.text for e in new_spec.xpath('overrides/field'))
    if old_overrides != new_overrides:
        changes.append(f"overrides: {old_overrides} -> {new_overrides}")

    old_deltas = {d.tag: d.text for d in old_spec.xpath('delta_requirements/*')}
    new_deltas = {d.tag: d.text for d in new_spec.xpath('delta_requirements/*')}
    if old_deltas != new_deltas:
        for tag in sorted(set(old_deltas.keys()) | set(new_deltas.keys())):
            old_val = old_deltas.get(tag, '<missing>')
            new_val = new_deltas.get(tag, '<missing>')
            if (
                tag == "notes"
                and docstring_changed
                and old_val == old_docstring
                and new_val == new_docstring
            ):
                continue
            if old_val != new_val:
                changes.append(f"delta.{tag}: {old_val} -> {new_val}")

    if docstring_changed:
        changes.append(_patch_block("docstring", old_docstring, new_docstring))

    old_desc = _node_text(old_spec, 'description')
    new_desc = _node_text(new_spec, 'description')
    if old_desc != new_desc:
        changes.append(
            f"description: {_summarize_text(old_desc) or '<missing>'} -> {_summarize_text(new_desc) or '<missing>'}"
        )

    old_notes = _node_text(old_spec, 'notes')
    new_notes = _node_text(new_spec, 'notes')
    if old_notes != new_notes:
        changes.append(
            f"notes: {_summarize_text(old_notes) or '<missing>'} -> {_summarize_text(new_notes) or '<missing>'}"
        )

    return changes


def _print_inherited_context(spec, specs_by_ref, shared_superspecs=None):
    inherits = [e.text for e in spec.xpath('inherits/ref')]
    if not inherits:
        return
    
    # Extract context from the child spec node
    child_context = {}
    context_node = spec.find("context")
    if context_node is not None:
        for child in context_node:
            child_context[child.tag] = child.text
            
    _print_inherited_specs(inherits, specs_by_ref, shared_superspecs, child_context)


def _print_inherited_specs(inherits, specs_by_ref, shared_superspecs=None, child_context=None):
    from jinja2 import Template
    inherited_specs, unresolved_refs = _inherited_specs(inherits, specs_by_ref)
    if inherited_specs:
        print("  inherited_specs:")
    for ref, spec_name, spec_node in inherited_specs:
        is_template = spec_node.get("template") == "true"
        if spec_node.get("template") is None:
            # Fallback for older XML specs
            req_text = _node_text(spec_node, "docstring") or _node_text(spec_node, "docstring_template") or ""
            is_template = "{{" in req_text or "{%" in req_text
        
        if is_template:
            print(f"    {spec_name}: {ref} (template instance)")
            requirement_text = _node_text(spec_node, "docstring") or _node_text(spec_node, "docstring_template")
            if requirement_text:
                if child_context:
                    try:
                        requirement_text = Template(requirement_text).render(**child_context).strip()
                    except Exception:
                        pass
                print("      requirement:")
                for line in requirement_text.splitlines():
                    print(f"        {line}")
        else:
            print(f"    {spec_name}: {ref}")
            if shared_superspecs is not None:
                shared_superspecs[ref] = spec_node
            else:
                # If no shared context, print in-place (e.g. in tests)
                requirement_text = _node_text(spec_node, "docstring") or _node_text(spec_node, "docstring_template")
                if requirement_text:
                    print("      requirement:")
                    for line in requirement_text.splitlines():
                        print(f"        {line}")

    if unresolved_refs:
        print("  unresolved_inherited_refs:")
        for ref in unresolved_refs:
            print(f"    {ref}")


def _print_inherited_docstrings(inherits, specs_by_ref):
    _print_inherited_specs(inherits, specs_by_ref)


def _inherited_docstrings(inherits, specs_by_ref):
    docs = []
    for ref in inherits:
        inherited_spec = specs_by_ref.get(ref)
        if inherited_spec is None:
            continue
        docstring = _node_text(inherited_spec, 'docstring')
        if docstring:
            docs.append((ref, docstring))
    return docs


def _inherited_context(inherits, specs_by_ref):
    docs = []
    unresolved_refs = []
    seen_refs = set()

    def visit(ref):
        if not ref or ref in seen_refs:
            return
        seen_refs.add(ref)

        inherited_spec = specs_by_ref.get(ref)
        if inherited_spec is None:
            unresolved_refs.append(ref)
            return

        docstring = _node_text(inherited_spec, 'docstring')
        if docstring:
            docs.append((ref, docstring))

        for child_ref in inherited_spec.xpath('inherits/ref'):
            visit(child_ref.text)

    for ref in inherits:
        visit(ref)

    return docs, unresolved_refs


def _inherited_specs(inherits, specs_by_ref):
    specs = []
    unresolved_refs = []
    seen_refs = set()

    def visit(ref):
        if not ref or ref in seen_refs:
            return
        seen_refs.add(ref)

        inherited_spec = specs_by_ref.get(ref)
        if inherited_spec is None:
            unresolved_refs.append(ref)
            return

        spec_name = inherited_spec.get("type") or ref.rsplit(".", 1)[-1]
        specs.append((ref, spec_name, inherited_spec))

        for child_ref in inherited_spec.xpath('inherits/ref'):
            visit(child_ref.text)

    for ref in inherits:
        visit(ref)

    return specs, unresolved_refs


if __name__ == "__main__":
    # Delegate to the unified CLI: `libspec diff <dir>`
    import sys as _sys
    from libspec.cli import main as _cli_main
    _sys.argv.insert(1, 'diff')
    _cli_main()
