import os
import tempfile
import difflib
from pathlib import Path
from lxml import etree
from xmldiff import main

def get_latest_xml_files(directory):
    path = Path(directory)
    xml_files = list(path.glob('*.xml'))
    if len(xml_files) == 0:
        return None
    
    file_info = []
    import datetime
    for f in xml_files:
        try:
            tree = etree.parse(str(f))
            root = tree.getroot()
            date_str = root.get('date-created')
            if date_str:
                file_info.append((date_str, f))
            else:
                # Fallback to file mtime formatted as ISO string
                mtime = os.path.getmtime(str(f))
                dt = datetime.datetime.fromtimestamp(mtime).astimezone()
                file_info.append((dt.isoformat(), f))
        except Exception:
            mtime = os.path.getmtime(str(f))
            dt = datetime.datetime.fromtimestamp(mtime).astimezone()
            file_info.append((dt.isoformat(), f))
    
    # Sort by the timestamp (date-created string or mtime)
    file_info.sort(key=lambda x: x[0])
    
    if len(file_info) == 1:
        # Only one spec exists — bootstrap case; diff against a null spec
        return None, file_info[-1][1]
    
    return file_info[-2][1], file_info[-1][1]

NULL_SPEC_XML = b"""<?xml version='1.0' encoding='utf-8'?>
<specification_set date-created="" />"""


def _node_text(spec, tag):
    node = spec.find(tag)
    if node is None or node.text is None:
        return ""
    return node.text.strip()


def _patch_block(label, old_text, new_text):
    old_lines = (old_text or "").splitlines()
    new_lines = (new_text or "").splitlines()
    diff_lines = list(
        difflib.unified_diff(
            old_lines,
            new_lines,
            fromfile=f"old/{label}",
            tofile=f"new/{label}",
            lineterm="",
        )
    )
    if not diff_lines:
        return f"{label}: <no textual changes>"
    return f"{label}:\n" + "\n".join(diff_lines)


def _spec_ref(spec):
    return spec.get("ref") or spec.get("type")


def _specs_by_ref(root):
    specs = {}
    for spec in root.xpath("//specification"):
        ref = _spec_ref(spec)
        if ref:
            specs[ref] = spec
    return specs


def _libspec_version(root):
    return root.get("libspec-version") or ""


def _major_version(version):
    major = version.split(".", 1)[0].strip()
    return int(major) if major.isdigit() else None


def _major_versions_compatible(old_root, new_root):
    old_major = _major_version(_libspec_version(old_root))
    new_major = _major_version(_libspec_version(new_root))
    return old_major is None or new_major is None or old_major == new_major


def _version_mismatch_message(old_file, new_file, old_root, new_root):
    return (
        "Error: refusing to diff specs generated by different libspec major versions "
        f"({old_file.name}: {_libspec_version(old_root) or '<missing>'}, "
        f"{new_file.name}: {_libspec_version(new_root) or '<missing>'}).\n"
        "Workaround: regenerate both XML specs with the same libspec major version, "
        "usually by rebuilding the older project commit with the current libspec, "
        "then rebuilding the current commit and diffing those generated files.\n"
        "See docs/cross-major-version-diffs.org for the full workflow and edge cases."
    )


def get_specs_for_diff(dir_arg):
    """Return (old_file, new_file, old_tree, new_root) for diffing."""
    files = get_latest_xml_files(dir_arg)
    if not files:
        return None, None, None, None

    old_file, new_file = files

    if old_file is None:
        try:
            new_tree = etree.parse(str(new_file))
            new_root = new_tree.getroot()
            return None, new_file, None, new_root
        except Exception as e:
            print(f"Error parsing XML: {e}")
            return None, None, None, None
    else:
        try:
            new_tree = etree.parse(str(new_file))
            new_root = new_tree.getroot()
            return old_file, new_file, None, new_root
        except Exception as e:
            print(f"Error parsing XML: {e}")
            return None, None, None, None


def _build_xml_root_from_db(build):
    from lxml import etree
    from libspec.store import DBSpec, DBEdge
    
    root = etree.Element("specification_set")
    root.set("id", build.session_id or build.master_hash[:16])
    root.set("date-created", build.created_at.isoformat())
    root.set("master-hash", build.master_hash)
    
    try:
        from importlib.metadata import version
        libspec_v = version("libspec")
    except Exception:
        libspec_v = "5.0.0"
    root.set("libspec-version", libspec_v)
    
    if build.git_commit:
        root.set("git-commit", build.git_commit)
        
    specs = DBSpec.select().where(DBSpec.build == build)
    for spec in specs:
        spec_elem = etree.SubElement(root, "specification")
        spec_elem.set("ref", spec.ref)
        spec_elem.set("type", spec.ref.split(".")[-1])
        spec_elem.set("template", "true" if spec.is_template else "false")
        spec_elem.set("hash", spec.hash)
        
        doc_tag = "docstring_template" if spec.is_template else "docstring"
        doc_elem = etree.SubElement(spec_elem, doc_tag)
        doc_elem.text = spec.docstring
        
        edges = DBEdge.select().where(DBEdge.build == build, DBEdge.child_ref == spec.ref).order_by(DBEdge.position.asc())
        inherits = [edge.parent_ref for edge in edges]
        if inherits:
            inherits_elem = etree.SubElement(spec_elem, "inherits")
            for parent in inherits:
                parent_ref = etree.SubElement(inherits_elem, "ref")
                parent_ref.text = parent
                
    return root


def generate_patch(dir_arg):
    """Generate a structured diff between the two latest XML specs or database builds."""
    if dir_arg is None:
        from libspec.store import get_store, SQLiteSpecStore, DBBuild, DBSpec
        store = get_store()
        if not isinstance(store, SQLiteSpecStore):
            print("Error: Active SpecStore is not a relational database store.")
            return
            
        try:
            # Query populated builds containing spec components (ignoring empty mock test builds)
            builds = (DBBuild.select()
                      .join(DBSpec)
                      .group_by(DBBuild.id)
                      .order_by(DBBuild.created_at.asc()))
            build_list = list(builds)
        except Exception:
            try:
                # Fall back to absolute latest builds
                build_list = list(DBBuild.select().order_by(DBBuild.created_at.asc()))
            except Exception as e:
                print(f"Error querying database builds: {e}")
                return
                
        if not build_list:
            print("Error: No snapshot builds found in the database. Compile a specification first.")
            return
            
        if len(build_list) == 1:
            old_build = None
            new_build = build_list[0]
        else:
            old_build = build_list[-2]
            new_build = build_list[-1]
            
        old_commit = f" (Git: {old_build.git_commit[:7]})" if old_build and old_build.git_commit else ""
        new_commit = f" (Git: {new_build.git_commit[:7]})" if new_build.git_commit else ""
        
        if old_build is None:
            print(f"Diffing State: <null spec> -> Build {new_build.session_id}{new_commit}")
            old_root = etree.fromstring(NULL_SPEC_XML)
        else:
            print(f"Diffing State: Build {old_build.session_id}{old_commit} -> Build {new_build.session_id}{new_commit}")
            old_root = _build_xml_root_from_db(old_build)
            
        new_root = _build_xml_root_from_db(new_build)
    else:
        old_file, new_file, _, new_root = get_specs_for_diff(dir_arg)
        if new_file is None:
            print("Error: No XML spec files found in the directory.")
            return

        try:
            old_root = etree.fromstring(NULL_SPEC_XML) if old_file is None else etree.parse(str(old_file)).getroot()
            if not _major_versions_compatible(old_root, new_root):
                print(_version_mismatch_message(old_file, new_file, old_root, new_root))
                return
        except Exception as e:
            print(f"Error parsing XML: {e}")
            return

        if old_file is None:
            print(f"Diffing State: <null spec> -> {new_file.name}")
        else:
            print(f"Diffing State: {old_file.name} -> {new_file.name}")
            
    print("=" * 60)

    old_specs = {s.get('type'): s for s in old_root.xpath('//specification')}
    new_specs = {s.get('type'): s for s in new_root.xpath('//specification')}
    new_specs_by_ref = _specs_by_ref(new_root)
    old_specs_by_ref = _specs_by_ref(old_root)

    all_components = sorted(set(old_specs.keys()) | set(new_specs.keys()))

    # 1. Identify changed components and collect their changes.
    # NOTE: We intentionally do NOT use _xml_diffs as a hard early-exit gate
    # here. _xml_diffs compares raw XML bytes; when only a superspec changes
    # (and it lives in a separate build artifact / XML file), the child spec
    # XML is byte-for-byte identical and _xml_diffs returns []. Skipping the
    # semantic comparison in that case silently hides inherited-spec changes.
    # Instead, always run the per-component semantic diff so that Inherits.diff()
    # can chase inherited refs and surface superspec mutations.
    diff_entries = []
    for comp_type in all_components:
        old_spec = old_specs.get(comp_type)
        new_spec = new_specs.get(comp_type)
        if old_spec is None:
            diff_entries.append(('NEW', comp_type, old_spec, new_spec, []))
        elif new_spec is None:
            diff_entries.append(('REMOVED', comp_type, old_spec, new_spec, []))
        else:
            changes = _compare_specs(old_spec, new_spec, old_specs_by_ref, new_specs_by_ref)
            if changes:
                diff_entries.append(('CHANGED', comp_type, old_spec, new_spec, changes))

    # 2. Also flag specs that reference superspecs not present in this XML.
    # When a child's XML is identical but it inherits an external ref, the diff
    # corpus cannot know whether that superspec changed. Surface the unresolved
    # refs so the developer knows to check cross-file inheritance manually.
    unresolved_by_comp = {}
    for comp_type, new_spec in new_specs.items():
        refs = [e.text for e in new_spec.xpath('inherits/ref') if e.text]
        unresolved = [r for r in refs if r not in new_specs_by_ref]
        if unresolved:
            unresolved_by_comp[comp_type] = unresolved

    if not diff_entries and not unresolved_by_comp:
        print("No changes detected.")
        return

    # 3. Print individual diffs
    for entry in diff_entries:
        action, comp_type, old_spec, new_spec, changes = entry
        if action == 'NEW':
            if _has_display_content(new_spec):
                print(f"\n[NEW] {comp_type}")
                _print_spec(new_spec, new_specs_by_ref)
        elif action == 'REMOVED':
            print(f"\n[REMOVED] {comp_type}")
        elif action == 'CHANGED':
            print(f"\n[CHANGED] {comp_type}")
            for change in changes:
                print(f"  - {change}")
            _print_inherited_context(new_spec, new_specs_by_ref)

    # 4. Warn about specs with unresolved inherited refs — these may mask
    # superspec changes that are invisible to the current diff corpus.
    if unresolved_by_comp:
        print("\n[WARNING] The following specs inherit refs that are not present")
        print("  in this XML. Changes to those superspecs cannot be detected here.")
        print("  Re-run the diff against the combined/merged spec XML to catch them.")
        for comp_type in sorted(unresolved_by_comp):
            for ref in unresolved_by_comp[comp_type]:
                print(f"  {comp_type} -> unresolved inherited ref: {ref}")


def _xml_diffs(old_file, new_file):
    if old_file is not None:
        return main.diff_files(str(old_file), str(new_file))

    with tempfile.NamedTemporaryFile(suffix='.xml', mode='wb', delete=False) as tmp:
        tmp.write(NULL_SPEC_XML)
        tmp_path = tmp.name
    try:
        return main.diff_files(tmp_path, str(new_file))
    finally:
        os.unlink(tmp_path)


class SpecField:
    """Base class for specification fields that can be displayed or compared."""
    TAGS = []

    def __init__(self, spec):
        self.spec = spec

    def get_value(self):
        """Extract value from top-level or delta_requirements."""
        for tag in self.TAGS:
            val = _node_text(self.spec, tag)
            if not val:
                val = _node_text(self.spec, f"delta_requirements/{tag}")
            if val:
                return val
        return ""

    def display(self, seen_values=None):
        pass

    def diff(self, old_spec):
        """Compare with old_spec and return a change string or list of strings."""
        return None


class Docstring(SpecField):
    TAGS = ["docstring", "docstring_template"]

    def display(self, seen_values=None):
        val = self.get_value()
        if val:
            lines = val.splitlines()
            print(f"  docstring: {lines[0]}")
            for line in lines[1:]:
                print(f"    {line}")
            if seen_values is not None:
                seen_values.add(val)

    def diff(self, old_spec):
        old_val = _node_text(old_spec, 'docstring') or _node_text(old_spec, 'docstring_template')
        new_val = _node_text(self.spec, 'docstring') or _node_text(self.spec, 'docstring_template')
        if old_val != new_val:
            return _patch_block("docstring", old_val, new_val)


class Title(SpecField):
    TAGS = ["title"]

    def display(self, seen_values=None):
        val = self.get_value()
        if val:
            print(f"  title: {val}")
            if seen_values is not None:
                seen_values.add(val)

    def diff(self, old_spec):
        old_val = _node_text(old_spec, 'title') or _node_text(old_spec, 'delta_requirements/title')
        new_val = self.get_value()
        if old_val != new_val:
            return f"title: {old_val or '<missing>'} -> {new_val or '<missing>'}"


class ReqId(SpecField):
    TAGS = ["req_id"]

    def display(self, seen_values=None):
        val = self.get_value()
        if val:
            print(f"  req_id: {val}")
            if seen_values is not None:
                seen_values.add(val)

    def diff(self, old_spec):
        old_val = _node_text(old_spec, 'req_id') or _node_text(old_spec, 'delta_requirements/req_id')
        new_val = self.get_value()
        if old_val != new_val:
            return f"req_id: {old_val or '<missing>'} -> {new_val or '<missing>'}"


class Description(SpecField):
    TAGS = ["description"]

    def display(self, seen_values=None):
        val = self.get_value()
        if val:
            print(f"  description: {val}")
            if seen_values is not None:
                seen_values.add(val)

    def diff(self, old_spec):
        old_val = _node_text(old_spec, 'description') or _node_text(old_spec, 'delta_requirements/description')
        new_val = self.get_value()
        if old_val != new_val:
            return f"description: {old_val or '<missing>'} -> {new_val or '<missing>'}"


class Notes(SpecField):
    TAGS = ["notes"]

    def display(self, seen_values=None):
        val = self.get_value()
        if val and (seen_values is None or val not in seen_values):
            print(f"  notes: {val}")
            if seen_values is not None:
                seen_values.add(val)

    def diff(self, old_spec):
        old_val = _node_text(old_spec, 'notes') or _node_text(old_spec, 'delta_requirements/notes')
        new_val = self.get_value()
        if old_val != new_val:
            return f"notes: {old_val or '<missing>'} -> {new_val or '<missing>'}"


class Inherits(SpecField):
    TAGS = ["inherits"]

    def __init__(self, spec, specs_by_ref=None, old_specs_by_ref=None, visited=None):
        super().__init__(spec)
        self.specs_by_ref = specs_by_ref
        self.old_specs_by_ref = old_specs_by_ref
        self.visited = visited or set()

    def display(self, seen_values=None):
        inherits = [e.text for e in self.spec.xpath('inherits/ref')]
        if inherits:
            child_context = _build_child_context(self.spec)
            _print_inherited_specs(inherits, self.specs_by_ref, child_context)

    def diff(self, old_spec):
        changes = []
        old_val = set(e.text for e in old_spec.xpath('inherits/ref|inherits/spec'))
        new_val = set(e.text for e in self.spec.xpath('inherits/ref|inherits/spec'))
        if old_val != new_val:
            changes.append(f"inherits: {old_val} -> {new_val}")
            
        if self.specs_by_ref and self.old_specs_by_ref:
            common_refs = old_val.intersection(new_val)
            for ref in sorted(common_refs):
                if ref in self.visited:
                    continue
                old_inherited = self.old_specs_by_ref.get(ref)
                new_inherited = self.specs_by_ref.get(ref)
                if old_inherited is not None and new_inherited is not None:
                    inherited_changes = _compare_specs(
                        old_inherited, new_inherited, 
                        self.old_specs_by_ref, self.specs_by_ref, 
                        self.visited
                    )
                    if inherited_changes:
                        changes.append(f"inherited spec '{ref}' changed")
                        
        return changes if changes else None


class EffectiveReqIds(SpecField):
    TAGS = ["effective_req_ids"]

    def display(self, seen_values=None):
        eff_ids = [e.text for e in self.spec.xpath('effective_req_ids/id')]
        if eff_ids:
            print(f"  effective_req_ids: {', '.join(eff_ids)}")

    def diff(self, old_spec):
        old_val = set(e.text for e in old_spec.xpath('effective_req_ids/id'))
        new_val = set(e.text for e in self.spec.xpath('effective_req_ids/id'))
        if old_val != new_val:
            return f"effective_req_ids: {old_val} -> {new_val}"


class Overrides(SpecField):
    TAGS = ["overrides"]

    def display(self, seen_values=None):
        overrides = [e.text for e in self.spec.xpath('overrides/field')]
        if overrides:
            print(f"  overrides: {', '.join(overrides)}")

    def diff(self, old_spec):
        old_val = set(e.text for e in old_spec.xpath('overrides/field'))
        new_val = set(e.text for e in self.spec.xpath('overrides/field'))
        if old_val != new_val:
            return f"overrides: {old_val} -> {new_val}"


class DeltaRequirements(SpecField):
    HANDLED_TAGS = {"docstring", "docstring_template", "title", "req_id", "description", "notes", "inherits", "effective_req_ids", "overrides"}

    def display(self, seen_values=None):
        deltas = self.spec.xpath('delta_requirements/*')
        if not deltas:
            return
            
        # Filter out fields already handled by Primary classes
        unique_deltas = []
        for d in deltas:
            val = (d.text or '').strip()
            if d.tag in self.HANDLED_TAGS:
                continue
            if seen_values is not None and val in seen_values:
                continue
            unique_deltas.append(d)
            
        if unique_deltas:
            print("  delta_requirements:")
            for d in unique_deltas:
                val = (d.text or '').strip()
                print(f"    {d.tag}: {val}")

    def diff(self, old_spec):
        old_docstring = _node_text(old_spec, 'docstring') or _node_text(old_spec, 'docstring_template')
        new_docstring = _node_text(self.spec, 'docstring') or _node_text(self.spec, 'docstring_template')
        docstring_changed = old_docstring != new_docstring

        old_deltas = {d.tag: d.text for d in old_spec.xpath('delta_requirements/*')}
        new_deltas = {d.tag: d.text for d in self.spec.xpath('delta_requirements/*')}
        
        changes = []
        if old_deltas != new_deltas:
            for tag in sorted(set(old_deltas.keys()) | set(new_deltas.keys())):
                old_val = old_deltas.get(tag, '<missing>')
                new_val = new_deltas.get(tag, '<missing>')
                if (
                    tag == "notes"
                    and docstring_changed
                    and old_val == old_docstring
                    and new_val == new_docstring
                ):
                    continue
                if old_val != new_val:
                    changes.append(f"delta.{tag}: {old_val} -> {new_val}")
        return changes


def _has_display_content(spec):
    """Check if a specification node has any content that would be displayed."""
    if _node_text(spec, 'docstring') or _node_text(spec, 'docstring_template'): return True
    if _node_text(spec, 'title'): return True
    if _node_text(spec, 'req_id'): return True
    if _node_text(spec, 'description'): return True
    if _node_text(spec, 'notes'): return True
    if spec.xpath('inherits/ref'): return True
    if spec.xpath('effective_req_ids/id'): return True
    if spec.xpath('overrides/field'): return True
    
    # Check for any delta_requirements that aren't standard tags
    deltas = spec.xpath('delta_requirements/*')
    handled = DeltaRequirements.HANDLED_TAGS
    if any(d.tag not in handled for d in deltas):
        return True
        
    return False


def _print_spec(spec, specs_by_ref=None):
    """Print the structured representation of a spec using polymorphic fields."""
    specs_by_ref = specs_by_ref or {}
    seen_values = set()

    fields = [
        Docstring(spec),
        Title(spec),
        ReqId(spec),
        Description(spec),
        Notes(spec),
        Inherits(spec, specs_by_ref),
        EffectiveReqIds(spec),
        Overrides(spec),
    ]

    for field in fields:
        field.display(seen_values)
        
    # DeltaRequirements handles everything else
    DeltaRequirements(spec).display(seen_values)


def _compare_specs(old_spec, new_spec, old_specs_by_ref=None, new_specs_by_ref=None, visited=None):
    """Compare two specs and return list of changes using polymorphic fields."""
    if visited is None:
        visited = set()
        
    spec_ref = _spec_ref(new_spec)
    if spec_ref in visited:
        return []
        
    current_visited = visited | {spec_ref} if spec_ref else visited
    
    changes = []
    
    # Define fields in the order they should appear in the diff output
    fields = [
        Title(new_spec),
        ReqId(new_spec),
        Inherits(new_spec, new_specs_by_ref, old_specs_by_ref, current_visited),
        EffectiveReqIds(new_spec),
        Overrides(new_spec),
        DeltaRequirements(new_spec),
        Docstring(new_spec),
        Description(new_spec),
        Notes(new_spec),
    ]

    for field in fields:
        diff_output = field.diff(old_spec)
        if diff_output:
            if isinstance(diff_output, list):
                changes.extend(diff_output)
            else:
                changes.append(diff_output)

    return changes


def _extract_context(node):
    """Recursively extract context from XML node."""
    ctx = {}
    if node is None:
        return ctx
    for child in node:
        if len(child) > 0:
            # Check if it's a list of items
            items = child.xpath('item')
            if items:
                ctx[child.tag] = [_extract_context_value(it) for it in items]
            else:
                ctx[child.tag] = _extract_context(child)
        else:
            ctx[child.tag] = (child.text or "").strip()
    return ctx


def _extract_context_value(node):
    """Extract value from a context node (either scalar or recursive)."""
    if len(node) == 0:
        return (node.text or "").strip()
    return _extract_context(node)


_STRUCTURAL_TAGS = {"context", "inherits", "source", "effective_req_ids", "overrides", "delta_requirements"}


def _build_child_context(spec):
    """Build template context from a spec node, merging context node, top-level fields, and delta_requirements."""
    # 1. Start with the explicit <context> node
    child_context = _extract_context(spec.find("context"))

    # 2. Merge top-level fields (like title, req_id) which templates often use
    for child in spec:
        if child.tag not in _STRUCTURAL_TAGS:
            val = (child.text or "").strip()
            if val and child.tag not in child_context:
                child_context[child.tag] = val

    # 3. Also merge from delta_requirements if present
    delta = spec.find("delta_requirements")
    if delta is not None:
        for child in delta:
            val = (child.text or "").strip()
            if val and child.tag not in child_context:
                child_context[child.tag] = val

    # 4. Fallback: feature_name defaults to the spec type (Feature.feature_name() returns __class__.__name__)
    if "feature_name" not in child_context:
        spec_type = spec.get("type")
        if spec_type:
            child_context["feature_name"] = spec_type

    return child_context


def _print_inherited_context(spec, specs_by_ref):
    inherits = [e.text for e in spec.xpath('inherits/ref')]
    if not inherits:
        return
    _print_inherited_specs(inherits, specs_by_ref, _build_child_context(spec))



def _print_inherited_specs(inherits, specs_by_ref, child_context=None):
    from jinja2 import Template
    inherited_specs, unresolved_refs = _inherited_specs(inherits, specs_by_ref)
    if inherited_specs:
        print("  inherited_specs (STRICTLY FOLLOW THE GUIDANCE BELOW):")
    for ref, spec_name, spec_node in inherited_specs:
        is_template = spec_node.get("template") == "true"
        if spec_node.get("template") is None:
            # Fallback for older XML specs
            req_text = _node_text(spec_node, "docstring") or _node_text(spec_node, "docstring_template") or ""
            is_template = "{{" in req_text or "{%" in req_text
        
        if is_template:
            print(f"    {spec_name}: {ref} (template instance)")
            requirement_text = _node_text(spec_node, "docstring") or _node_text(spec_node, "docstring_template")
            if requirement_text:
                # Always try to render if it's a template instance
                try:
                    requirement_text = Template(requirement_text).render(**(child_context or {})).strip()
                except Exception:
                    pass
                print("      requirement:")
                for line in requirement_text.splitlines():
                    print(f"        {line}")
        else:
            print(f"    {spec_name}: {ref}")
            requirement_text = _node_text(spec_node, "docstring") or _node_text(spec_node, "docstring_template")
            if requirement_text:
                print("      requirement:")
                for line in requirement_text.splitlines():
                    print(f"        {line}")

    if unresolved_refs:
        print("  unresolved_inherited_refs:")
        for ref in unresolved_refs:
            print(f"    {ref}")





def _inherited_specs(inherits, specs_by_ref):
    specs = []
    unresolved_refs = []
    seen_refs = set()

    def visit(ref):
        if not ref or ref in seen_refs:
            return
        seen_refs.add(ref)

        inherited_spec = specs_by_ref.get(ref)
        if inherited_spec is None:
            unresolved_refs.append(ref)
            return

        spec_name = inherited_spec.get("type") or ref.rsplit(".", 1)[-1]
        specs.append((ref, spec_name, inherited_spec))

        for child_ref in inherited_spec.xpath('inherits/ref'):
            visit(child_ref.text)

    for ref in inherits:
        visit(ref)

    return specs, unresolved_refs


if __name__ == "__main__":
    # Delegate to the unified CLI: `libspec diff <dir>`
    import sys as _sys
    from libspec.cli import main as _cli_main
    _sys.argv.insert(1, 'diff')
    _cli_main()
