"""
CLI command specifications.
"""

from .err import Feat, Req


class CLI(Req):
    """
    The libspec command-line interface is implemented with the Click library.

    The top-level CLI defines seven subcommands:
    - init: Scaffolds a new spec/ directory in the workspace.
    - build: Generates the XML specification and registers it with the SpecStore.
    - diff: Displays a structured semantic diff between two specifications.
    - mcp: Launches the Model Context Protocol (MCP) server over stdio.
    - mcp_agent: Configures project-local coding agent integrations.
    - repl: Starts the interactive specification inspector REPL shell.
    - link: Late-binds an active spec snapshot to a VCS revision (commit hash).

    The --version option reports the installed package version.
    Help is available via --help.
    """


class ClickCLIStructure(Feat):
    """
    Unified command-line interface structure using the Click library.
    """


class MainCliGroup(Req):
    """
    Define a central click Group `main` that manages the entrypoint, handling
    common options like `--version` and `--help`.
    """


class SubcommandRegistration(Req):
    """
    Define all seven subcommands as click commands under the main group:
    - `init`
    - `build` with `<spec_file>` argument and optional `-o` / `--output` option.
    - `diff` with optional `[build_dir]` argument.
    - `mcp`
    - `mcp_agent` with optional `<agent>` and `<project_root>` arguments, and `--list` flag.
    - `repl`
    - `link` with optional `--snapshot`, and required `--revision` options.
    """


class CliBackwardCompatibility(Req):
    """
    Ensure seamless backward compatibility with all active CLI usages, argument
    orderings, option defaults, and exit codes.
    """


class CliParameterValidation(Req):
    """
    Implement professional click-based validation and clean parameter types
    (such as click.Path) for paths and directories where applicable.
    """


class InitCommand(Feat):
    """
    `libspec init` scaffolds a new spec/ directory in the current working
    directory with three starter files:

    - spec/__init__.py (empty)
    - spec/main_spec.py (a MainSpec(Spec) class wired to the app module)
    - spec/app.py (placeholder App and CmdLine classes)
    - spec/err.py (Err base class + Feat/Req convenience aliases)

    The command exits with an error if a spec/ directory already exists,
    preventing accidental overwrite of an existing specification.
    """


class BuildCommand(Feat):
    """
    `libspec build <spec_file> [-o <output_dir>]` generates the XML
    specification from a Python spec file.

    Module loading strategy:
    - The spec file path is converted to a dotted module name relative to the
      current working directory (e.g. spec/main_spec.py -> spec.main_spec).
    - The CWD is prepended to sys.path so that relative imports within the spec
      package resolve correctly.
    - The module is imported via importlib.import_module() so that __package__
      is set correctly for relative imports (e.g. `from . import app`).

    Discovery strategy:
    - If the module contains an explicit Spec subclass, it is instantiated and
      `write_xml(output_dir)` is called directly.
    - Otherwise, all Ctx subclasses in the module are discovered via
      `module_specs()` and wrapped in an ad-hoc Spec for output.
    """


class XmlBuildDeprecation(Req):
    """
    Emitting XML specifications to a local output directory (such as `-o spec-build`)
    is deprecated and scheduled for removal in libspec version 7.0.0.

    Requirements:
    1. If the user invokes `libspec build` with a directory option (`-o` or `--output`),
       or calls `write_xml()` with an `output_dir` argument, the system must print
       a prominent deprecation warning to standard error.
    2. Raise a Python `DeprecationWarning` programmatically to allow developer
       environments to detect usage of the deprecated path.
    3. Encourage the user to transition to using the active database-backed
       SpecStore instead.
    """


class DiffCommand(Feat):
    """
    `libspec diff [<build_dir>]` diffs two specifications and prints a
    structured human-readable report.

    If `<build_dir>` is provided, it diffs the two most recent XML spec files
    in that directory. If `<build_dir>` is omitted (default), it reads directly
    from the active SQLite database store, diffing the two most recent
    snapshots.

    The two snapshots/files to diff are identified by chronological creation
    timestamps. Bootstrap case: if only one snapshot/file exists, a null spec
    (an empty <specification_set>) is used as the "old" specification so that
    the first build produces a useful "everything is new" diff.

    The diff refuses to run if the two versions were generated by different
    libspec major versions and prints a clear remediation message.
    """


class McpCommand(Feat):
    """
    `libspec mcp` launches the MCP (Model Context Protocol) server over.

    stdio, making the MCP tools available to any MCP-capable LLM client:
    - libspec_build
    - libspec_diff

    The MCP server is implemented with the FastMCP library and delegates to the
    same underlying logic as the CLI subcommands.
    """


class McpAgentCommand(Feat):
    """
    `libspec mcp_agent (<agent> [DIR] | --list)` automates local coding agent
    integrations.

    The command:
    - Scopes and validates agent identifiers (Antigravity, Gemini, Claude,
      OpenCode, Codex).
    - Writes project-local agent configurations, pointing to `uv run libspec
      mcp` to utilize the local environment.
    - Installs the libspec skill set via SkillKit's discovery specifications.
    """


class LinkCommand(Feat):
    """
    `libspec link [--snapshot <snapshot_id>] [--vcs <vcs_type>] --revision <revision> [--metadata <key=val>]`
    links a compiled spec snapshot to a version control system revision.

    The command:
    - Resolves the target snapshot ID (defaults to unlinked/pending snapshots,
      falling back to the current active snapshot if all are linked).
    - Appends the VCS link event to the SpecStore to late-bind metadata to the snapshot.
    """


class ReplCommand(Feat):
    """
    `libspec repl` launches the interactive specification inspector REPL shell.

    The command:
    - Connects to the active database or XML SpecStore fallback dynamically.
    - Launches a Read-Eval-Print Loop supporting real-time tab-completion and
      colorized inspector commands natively.
    """
