'''
CLI command specifications.
'''

from .err import Feat, Req


class CLI(Req):
    '''The libspec command-line interface is implemented with docopt-ng.

    The top-level usage string defines seven subcommands:
      libspec init
      libspec build <spec_file> [-o <output_dir>]
      libspec diff [<build_dir>]
      libspec mcp
      libspec mcp_agent (<agent> [<project_root>] | --list)
      libspec migrate <v4_build_dir>
      libspec repl

    The --version flag reports the installed package version via
    importlib.metadata. Help is available via -h / --help.

    The default output directory for `build` is `spec-build`.
    '''


class InitCommand(Feat):
    '''`libspec init` scaffolds a new spec/ directory in the current working
    directory with three starter files:

    - spec/__init__.py (empty)
    - spec/main_spec.py (a MainSpec(Spec) class wired to the app module)
    - spec/app.py (placeholder App and CmdLine classes)
    - spec/err.py (Err base class + Feat/Req convenience aliases)

    The command exits with an error if a spec/ directory already exists,
    preventing accidental overwrite of an existing specification.
    '''


class BuildCommand(Feat):
    '''`libspec build <spec_file> [-o <output_dir>]` generates the XML
    specification from a Python spec file.

    Module loading strategy:
    - The spec file path is converted to a dotted module name relative to
      the current working directory (e.g. spec/main_spec.py -> spec.main_spec).
    - The CWD is prepended to sys.path so that relative imports within the
      spec package resolve correctly.
    - The module is imported via importlib.import_module() so that
      __package__ is set correctly for relative imports (e.g. `from . import app`).

    Discovery strategy:
    - If the module contains an explicit Spec subclass, it is instantiated
      and `write_xml(output_dir)` is called directly.
    - Otherwise, all Ctx subclasses in the module are discovered via
      `module_specs()` and wrapped in an ad-hoc Spec for output.
    '''


class DiffCommand(Feat):
    '''`libspec diff [<build_dir>]` diffs two specifications and prints a
    structured human-readable report.

    If `<build_dir>` is provided, it diffs the two most recent XML spec files in
    that directory. If `<build_dir>` is omitted (default), it reads directly from
    the active SQLite database store, diffing the two most recent snapshots.

    The two snapshots/files to diff are identified by chronological creation
    timestamps. Bootstrap case: if only one snapshot/file exists, a null spec
    (an empty <specification_set>) is used as the "old" specification so that the
    first build produces a useful "everything is new" diff.

    The diff refuses to run if the two versions were generated by different
    libspec major versions and prints a clear remediation message.
    '''


class McpCommand(Feat):
    '''`libspec mcp` launches the MCP (Model Context Protocol) server over
    stdio, making the MCP tools available to any MCP-capable LLM client:
    - libspec_build
    - libspec_diff

    The MCP server is implemented with the FastMCP library and delegates
    to the same underlying logic as the CLI subcommands.
    '''


class McpAgentCommand(Feat):
    '''`libspec mcp_agent (<agent> [DIR] | --list)` automates local coding agent integrations.

    The command:
    - Scopes and validates agent identifiers (Antigravity, Gemini, Claude, OpenCode, Codex).
    - Writes project-local agent configurations, pointing to `uv run libspec mcp` to utilize the local environment.
    - Installs the libspec skill set via SkillKit's discovery specifications.
    '''


class MigrateCommand(Feat):
    '''`libspec migrate <v4_build_dir>` upgrades workspace assets from v4.2.0 (XML hashed files)
    to version 5.0.0 (unified SpecStore).

    The command:
    - Parses all historical hashed XML files under the source directory chronologically.
    - Performs atomic bulk loading of snapshots, maintaining exact original timestamp values.
    - Resolves and populates relational database targets under Peewee schemas or clean v5 locations.
    '''


class ReplCommand(Feat):
    '''`libspec repl` launches the interactive specification inspector REPL shell.

    The command:
    - Connects to the active database or XML SpecStore fallback dynamically.
    - Launches a Read-Eval-Print Loop supporting real-time tab-completion and colorized inspector commands natively.
    '''
